requires 'perl', '5.016';
requires 'Class::Tiny';
requires 'Net::Nostr::Event';
requires 'strictures', '2';

on configure => sub {
    requires 'strictures', '2';
};

on develop => sub {
    requires 'Test::Pod', '1.52';
};
