requires 'perl', '5.016';
requires 'Class::Tiny';
requires 'Net::Nostr::Event';
requires 'strictures', '2';

on configure => sub {
    requires 'ExtUtils::MakeMaker', '6.64';
    requires 'strictures', '2';
};

on test => sub {
    requires 'Test::More', '0.98';
};

on develop => sub {
    requires 'Test::Pod', '1.52';
};
