requires 'perl', '5.016';
requires 'Net::Blossom', '0.001';
requires 'strictures', '2';

on configure => sub {
    requires 'strictures', '2';
};

on develop => sub {
    requires 'Test::Pod', '1.52';
};
